### ISSUE TITLE
Cannot use object of type DOMNodeList as array

### ISSUE THREAD

**Issue by xangxiong** [infostreams/excel-merge#1]
First off, thanks for the great library for merging excel.  I'm currently using PHP 5.3.3 on a CentOS 6 box and I get a fatal error when trying to merge 2 excel files regarding using DOMNodeList as an array in the Tasks/Styles.php file.

If I change all $elems[0] to $elems->item(0), I no longer get a fatal error and the excel generates successfully.  Could you review the fix and see if you can apply it to your Master release.  I want to continue and use your repository.

**Comment by infostreams** [comment]
Hi xangxiong, 

Thanks! I don't have PHP5.3 anymore, but this is the second time I got this report and it's backed by the PHP documentation so I just went ahead and made this change. It's in version 0.8.2 that I released just now (see https://github.com/infostreams/excel-merge/tree/0.8.2). You should be able to install it by running `composer update`. Can you check if it works? Thanks for pointing out this issue and providing a fix! And it would be great if you can star the repository if you use and like it :-)

**Comment by xangxiong** [comment]
Thanks infostreams. I've confirmed the fatal errors are fixed.
