### ISSUE TITLE
Add PR #13 to a new tag 

### ISSUE THREAD

**Issue by alexandreacid** [infostreams/excel-merge#17]
Hi,

I've just discovered your lib after running into memory issues while merging XSLX files.

All works great ONLY with the modification done on PR #13 . However, this change is only available on your master branch. Could you create a tag with this modification to obtain a stable version via composer install ?

**Comment by infostreams** [comment]
Thanks! I think I did that, but via the GitHub interface so I'm not 100% sure if it worked. Check https://github.com/infostreams/excel-merge/releases/tag/0.8.6

Does that work for you?

**Comment by alexandreacid** [comment]
Unfortunately this last tag is missing on Packagist https://packagist.org/packages/infostreams/excel-merge...

It looks like your package is not auto updated.

**Comment by infostreams** [comment]
I tried setting up auto update but it complains. I did all the steps though 🤷‍♂️ Nevertheless, I now did a manual update. I see version 0.8.6 on packagist as well.

Thanks for flagging this!
