### ISSUE TITLE
Merged file is broken

### ISSUE THREAD

**Issue by babblo** [infostreams/excel-merge#18]
Hello, I'm trying to merge a .xlsm and a .xlsx files together. The first one is my "template" file with only a couple of macros, the second one only have 3 lines to test. I'm unable to figure the issue. Maybe can you take a look? 

Thanks in advance.

[test.zip](https://github.com/infostreams/excel-merge/files/15157197/test.zip)

**Comment by babblo** [comment]
Well, the template and data files has got some hidden sheets, after removed Excel keeps complaining about damages in file but it's able to open it. I'm attaching the new merged file. 

[merged2.zip](https://github.com/infostreams/excel-merge/files/15157251/merged2.zip)

**Comment by infostreams** [comment]
Hi sorry, this code is provided as-is and is more or less unmaintained. Sorry about that.
