### ISSUE TITLE
how can i integrate this with my laravel 5.2 ? 

### ISSUE THREAD

**Issue by kurianic** [infostreams/excel-merge#7]
I am facing issue with time delay for creating and merging .xlsx file. My search for fast merging ended here but now i don't know how to integrate our class with my laravel ?

**Comment by sivaneshc** [comment]
Hi
Any update. How to integrate in laravel?

**Comment by infostreams** [comment]
You can just `composer require infostreams/excel-merge` and then in your code do `$xls = new \ExcelMerge\ExcelMerge()`...?
