### ISSUE TITLE
Getting ZipArchive::extractTo(): Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by mansouralex** [infostreams/excel-merge#8]
Hi @infostreams ,  

I'm just getting the following `ErrorException  : ZipArchive::extractTo(): Invalid or uninitialized Zip object` at /vendor/infostreams/excel-merge/ExcelMerge.php:208

Do you have any thoughts why it's taking place? Thanks.

**Comment by infostreams** [comment]
Hi,

Do you have an example excel file where this happens? Thanks!

**Comment by infostreams** [comment]
Closed due to lack of activity
